In [3]:
#Import NumPy as its abbreviation 'np'
import numpy as np

In [4]:
#Create a 1-dimensional NumPy array using np.array()
ar1 = np.array([1,2,3,4])
print("1-dimensional array : ")
print(ar1)

#Create a 2-dimensional NumPy array using np.array()
ar2 = np.array([[2,4,6,8,10],[1,3,5,7,9]])
print("2-dimensional array : ")
print(ar2)

1-dimensional array : 
[1 2 3 4]
2-dimensional array : 
[[ 2  4  6  8 10]
 [ 1  3  5  7  9]]


In [5]:
#Attributes of 1-dimensional array(shape, number of dimensions, data type, size and type)
ar1.shape,ar1.ndim,ar1.dtype,ar1.size,type(ar1)

((4,), 1, dtype('int64'), 4, numpy.ndarray)

In [8]:
#Attributes of 2-dimensional array
ar2.shape, ar2.ndim, ar2.dtype, ar2.size, type(ar2)

((2, 5), 2, dtype('int64'), 10, numpy.ndarray)

In [9]:
#Create an array of shape (5,5) with only ones
ar3 = np.ones([5,5])
ar3

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
#Create array of shape (3,3,5) with only zeros
ar4 = np.zeros((3,3,5))
ar4

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [11]:
#Create a random array with numbers between 0 and 10 of size(7,2)
np.random.randint(10, size=(7,2))

array([[8, 5],
       [3, 0],
       [6, 5],
       [4, 7],
       [7, 0],
       [0, 6],
       [4, 9]])

In [12]:
#Create a random array of floats between 0 and 1 of shape (3,5)
np.random.random((3,5))

array([[0.65103679, 0.57548422, 0.95011633, 0.47395565, 0.7746441 ],
       [0.39532065, 0.82207544, 0.4227589 , 0.7271005 , 0.82458603],
       [0.90393578, 0.70003569, 0.12872622, 0.31458475, 0.08022761]])

In [15]:
#Create an array of normally distributed random numbers
np.random.randn(int(input("number1 : ")),int(input("number2 : ")))

number1 :  6
number2 :  7


array([[-0.44122003,  0.84203651,  0.37385523,  0.66277965, -0.74609404,
        -0.84277855, -0.70980657],
       [-1.63252107,  0.66863981, -1.40718847, -2.2806551 , -1.7538543 ,
        -0.09805761,  1.39142534],
       [ 1.15572634, -0.41383921,  1.24710173, -1.18962952, -0.64716601,
        -0.15335416,  0.74267387],
       [-0.03823222,  2.36689079,  1.12621351, -0.79576367, -1.49918365,
        -0.72536482, -2.31724386],
       [-0.26542426, -0.51877434, -0.07934649,  0.63766972, -1.53874892,
        -1.84698715,  1.94109226],
       [ 0.68523691, -0.1485882 ,  1.59631581,  0.58724035, -0.39972519,
        -0.12941835,  0.41031864]])

In [18]:
#set the random seed to 42
#Create a random array of numbers between 0 and 10 of size (4,6)
np.random.seed(42)
np.random.randint(10,size=(4,6))

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [20]:
#Copy the code from the cell above and run it again
np.random.seed(42)
rand = np.random.randint(10,size=(4,6))
rand

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [21]:
#Find the 0'th index of the 1 atleast array you created
rand[0]

array([6, 3, 7, 4, 6, 9])

In [22]:
#Get the first 2 rows of late st array you created
rand[:2]

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7]])

In [23]:
#Get the first 2 values of the first 2 rows of the latest array
rand[:2,:2]

array([[6, 3],
       [2, 6]])

In [26]:
#Create a random array of numbers between 0 & 10 and an array of ones both of size (3,5),save them both to variables
ran = np.random.randint(10,size = (3,5))
ones = np.ones((3,5))
ran,ones

(array([[7, 3, 1, 5, 5],
        [9, 3, 5, 1, 9],
        [1, 9, 3, 7, 6]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [27]:
#Add the two arrays together
ran+ones

array([[ 8.,  4.,  2.,  6.,  6.],
       [10.,  4.,  6.,  2., 10.],
       [ 2., 10.,  4.,  8.,  7.]])

In [28]:
#Create another array of ones of shape(5,3)
ones1 = np.ones((5,3))
ones1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [29]:
#Try add the array of ones and the other most recent array together
#you can anticipate an error
ran+ones1

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

In [30]:
#Do the same operation you just did but this time with a transpose on one array
tra = ran+ones1.T
tra

array([[ 8.,  4.,  2.,  6.,  6.],
       [10.,  4.,  6.,  2., 10.],
       [ 2., 10.,  4.,  8.,  7.]])

In [32]:
#Take the latest array to the power of 2 using the python way
tra**2

array([[ 64.,  16.,   4.,  36.,  36.],
       [100.,  16.,  36.,   4., 100.],
       [  4., 100.,  16.,  64.,  49.]])

In [33]:
#Do the same thing with numpy way
np.power(tra,2)

array([[ 64.,  16.,   4.,  36.,  36.],
       [100.,  16.,  36.,   4., 100.],
       [  4., 100.,  16.,  64.,  49.]])

In [35]:
#Find the mean, min, max, standard deviation, variance of the latest array using np.mean()
np.mean(tra),np.min(tra),np.max(tra),np.std(tra),np.var(tra)

(5.933333333333334, 2.0, 10.0, 2.792052212182923, 7.795555555555556)

In [36]:
#Create two arrays of random of random integers between 0 to 10 one of size(3,3) the other of size(3,2)
a1 = np.random.randint(10,size=(3,3))
a2 = np.random.randint(10,size=(3,2))
a1,a2

(array([[8, 7, 4],
        [1, 4, 7],
        [9, 8, 8]]),
 array([[0, 8],
        [6, 8],
        [7, 0]]))

In [37]:
#perform a dot product on the two newest arrays you created
np.dot(a1,a2)

array([[ 70, 120],
       [ 73,  40],
       [104, 136]])

In [38]:
#Create two arrays of random integers between 0 to 10 both of size (4,3)
b1 = np.random.randint(10,size=(4,3))
b2 = np.random.randint(10,size=(4,3))
b1,b2

(array([[7, 7, 2],
        [0, 7, 2],
        [2, 0, 4],
        [9, 6, 9]]),
 array([[8, 6, 8],
        [7, 1, 0],
        [6, 6, 7],
        [4, 2, 7]]))

In [39]:
#Perform a hadamard product on the two newest arrays you created
b1*b2

array([[56, 42, 16],
       [ 0,  7,  0],
       [12,  0, 28],
       [36, 12, 63]])

In [41]:
#Perform a dot product on the two newest arrays you ceated 
#Error anticipated
np.dot(b1,b2)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

In [42]:
#Take the latest two arrays,perform a transpose on one of them and then perform a dot product on them both
np.dot(b1.T,b2)

array([[104,  72, 133],
       [129,  61,  98],
       [ 90,  56, 107]])

In [43]:
#Create two arrays of random integers between 0 and 10 of the same shape and save them to variables
c1 = np.random.randint(10,size=(2,3))
c2 = np.random.randint(10,size=(2,3))
c1,c2

(array([[5, 2, 0],
        [2, 4, 2]]),
 array([[0, 4, 9],
        [6, 6, 8]]))

In [44]:
#Compare the two arrays with '>','<='and '=='
c1>c2

array([[ True, False, False],
       [False, False, False]])

In [45]:
c1<=c2

array([[False,  True,  True],
       [ True,  True,  True]])

In [46]:
c1==c2

array([[False, False, False],
       [False, False, False]])

In [48]:
#Sort one of the arrays you just created in ascending order
np.sort(c1)

array([[0, 2, 5],
       [2, 2, 4]])

In [49]:
#Sort the indexes of one of the arrays you just created
np.argsort(c1)

array([[2, 1, 0],
       [0, 2, 1]])

In [50]:
#Find the index with the maximum value in one of the arrays you've created
np.argmax(c1)

0

In [52]:
#Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [53]:
#Find the indexes with the maximum values down the vertical axis of one of the arrays you created
np.argmax(c1,axis = 1)

array([0, 1])

In [ ]:
#Find the indexes with the minimum values across the horizontal 